name: Python Build and Test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print a message
        run: echo "Hello, this is the build and testing_layer workflow!"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests selenium jira pytest-html

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Setup EdgeDriver
        uses: browser-actions/setup-chromium@v1
        with:
          edge-version: latest

      - name: Run Selenium Test
        run: python -m unittest C:/Users/odehm/Desktop/repos/petsore/test/test_api/test_cart.py

      - name: Run passwordLogic testing_layer
        run: python -m unittest C:/Users/odehm/Desktop/repos/petsore/test/test_ui/Add_to_cart.py
